# Generated by Django 4.2.5 on 2023-09-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'إنشاء حسابات المدربين ', 'verbose_name_plural': 'إنشاء حسابات المدربين'},
        ),
    ]
