# Generated by Django 4.2.5 on 2023-09-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'إدارة الحسابات', 'verbose_name_plural': 'إدارة الحسابات'},
        ),
    ]
