# Generated by Django 4.2.5 on 2023-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
